# Generated by Django 5.1.5 on 2025-01-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./uploads/')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('entry', models.PositiveSmallIntegerField()),
                ('initial_comment', models.TextField()),
                ('final_comment', models.TextField()),
                ('previous', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scambaiting.email')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scambaiting.email')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scambaiting.image')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('display_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scambaiting.image')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='scambaiting.person'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='scambaiting.person'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scambaiting.thread'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('thread', 'entry'), name='unique entry for thread'),
        ),
    ]
