# Generated by Django 5.1.5 on 2025-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(to='scambaiting.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
