# Generated by Django 5.1.5 on 2025-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='previous',
        ),
        migrations.AlterField(
            model_name='email',
            name='final_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='initial_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
