# Generated by Django 5.1.5 on 2025-01-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0002_remove_email_previous_alter_email_final_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
