# Generated by Django 5.1.6 on 2025-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0002_email_cc_person_bio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='email',
            name='unique entry for thread',
        ),
        migrations.RemoveField(
            model_name='email',
            name='entry',
        ),
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='has_inbox',
            field=models.BooleanField(default=False),
        ),
    ]
