# Generated by Django 5.1.6 on 2025-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0003_remove_email_unique_entry_for_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
