# Generated by Django 5.1.5 on 2025-01-29 08:29

import scambaiting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0003_remove_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('short_id', models.CharField(max_length=50, unique=True, validators=[scambaiting.validators.no_spaces])),
            ],
        ),
    ]
