# Generated by Django 5.1.6 on 2025-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0004_thread_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(blank=True, null=True, to='scambaiting.person'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
