# Generated by Django 5.1.6 on 2025-03-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0005_alter_email_cc_alter_email_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['timestamp']},
        ),
    ]
