# Generated by Django 5.1.6 on 2025-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambaiting', '0008_person_baiter_alter_email_body_alter_email_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='correspondents',
            field=models.ManyToManyField(blank=True, to='scambaiting.person'),
        ),
    ]
